# Generated by Django 4.0.5 on 2022-06-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('embarque', 'embarque'), ('descarga', 'descarga'), ('gate in', 'gate in'), ('gate out', 'gate out'), ('reposicionamento', 'reposicionamento'), ('pesagem', 'pesagem'), ('scanner', 'scanner')], max_length=16)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=11)),
                ('tipo', models.IntegerField(choices=[(20, 20), (40, 40)])),
                ('status', models.CharField(choices=[('cheio', 'cheio'), ('vazio', 'vazio')], max_length=5)),
                ('categoria', models.CharField(choices=[('importação', 'importação'), ('exportação', 'exportação')], max_length=10)),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container', to='api.movimentacao')),
            ],
        ),
    ]
